name: Build and Deploy JavaFX Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0

      - name: Set up JDK 23
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Package the application as a JAR
        run: mvn package

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: advent-calendar-jar
          path: target/*.jar

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.LELELE }}
          publish_dir: ./target